export const SORA_IMG = "https://i.imgur.com/PvYs6dc.png";

export const GET_ALL_WAIFUS = 'GET_ALL_WAIFUS';
export type GET_ALL_WAIFUS = typeof GET_ALL_WAIFUS;

export const SET_FIRST_FETCH = 'SET_FIRST_FETCH';
export type SET_FIRST_FETCH = typeof SET_FIRST_FETCH;

export const GET_USER_WAIFUS = 'GET_USER_WAIFUS';
export type GET_USER_WAIFUS = typeof GET_USER_WAIFUS;

export const GET_WAIFU_RARITIES = 'GET_WAIFU_RARITIES';
export type GET_WAIFU_RARITIES = typeof GET_WAIFU_RARITIES;

export const GET_GUILD_LEADERBOARD = 'GET_GUILD_LEADERBOARD';
export type GET_GUILD_LEADERBOARD = typeof GET_GUILD_LEADERBOARD;

export const GET_GLOBAL_LEADERBOARD = 'GET_GLOBAL_LEADERBOARD';
export type GET_GLOBAL_LEADERBOARD = typeof GET_GLOBAL_LEADERBOARD;

export const GET_SORA_STATS = 'GET_SORA_STATS';
export type GET_SORA_STATS = typeof GET_SORA_STATS;
